[build]
  publish = "dist"
  command = "npx update-browserslist-db@latest"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [build.environment]
SECRETS_SCAN_OMIT_PATHS = "supabase/functions/check-subscription"
